### ISSUE TITLE
Fix EntityDeathEvent error

### ISSUE THREAD

**Issue by Mapetr** [uwuPlugins/uwuJobs#80]
Here is the error in full

```[17:44:42 ERROR]: Could not pass event EntityDeathEvent to uwuJobs v2024.603.0-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)" is null
        at uwuJobs-2024.603.0-SNAPSHOT.jar/me.yellowbear.uwujobs.Job.handleJobEvent(Job.java:46) ~[uwuJobs-2024.603.0-SNAPSHOT.jar:?]
        at uwuJobs-2024.603.0-SNAPSHOT.jar/me.yellowbear.uwujobs.UwuJobs.onEntityDeath(UwuJobs.java:124) ~[uwuJobs-2024.603.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor51.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-131-ac64751]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:987) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1873) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1767) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1584) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1339) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2376) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.onAttack(ServerGamePacketListenerImpl.java:2851) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2762) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-131-ac64751]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by MartinRostejnsky** [comment]
I am not able to replicate this issue on 2023.925.0
